### ISSUE TITLE
UnicodeDecodeError when running wut

### ISSUE THREAD

**Issue by jenwirth** [shobrook/wut#19]
Hi,

I have installed it, set my Open API key and started a screen session. When i run `wut` i get `UnicodeDecodeError`: 
```
> wut
Traceback (most recent call last):
  File "/home/jen/.local/bin/wut", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/home/jen/.local/lib/python3.13/site-packages/wut/wut.py", line 62, in main
    terminal_context = get_terminal_context(shell)
  File "/home/jen/.local/lib/python3.13/site-packages/wut/utils.py", line 290, in get_terminal_context
    pane_output = get_pane_output()
  File "/home/jen/.local/lib/python3.13/site-packages/wut/utils.py", line 139, in get_pane_output
    output = f.read()
  File "<frozen codecs>", line 325, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 37: invalid start byte
```

**Comment by shobrook** [comment]
Thanks for pointing this out. Just pushed a fix. Try upgrading the package and let me know if it works now:

```bash
> pipx upgrade wut-cli
```

**Comment by jenwirth** [comment]
Wow that is fast :) 

Works like a charm.

love the idea of this tool.
